apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      containers:
      - name: portainer
        image: portainer/portainer-ce:alpine
        ports:
        - containerPort: 9000
        - containerPort: 9443
        volumeMounts:
        - name: data
          mountPath: /data
        - name: docker-sock
          mountPath: /var/run/docker.sock
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
      volumes:
      - name: data
        emptyDir: {}
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
---
apiVersion: v1
kind: Service
metadata:
  name: portainer-svc
  namespace: homelab
spec:
  selector:
    app: portainer
  ports:
  - name: http
    port: 80
    targetPort: 9000
  - name: https
    port: 443
    targetPort: 9443
  type: LoadBalancer
