apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
      - name: uptime-kuma
        image: louislam/uptime-kuma:1
        ports:
        - containerPort: 3001
        volumeMounts:
        - name: data
          mountPath: /app/data
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-svc
  namespace: homelab
spec:
  selector:
    app: uptime-kuma
  ports:
  - port: 80
    targetPort: 3001
  type: LoadBalancer
